CREATE TABLE CUSTOMERS (
    ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50),
    AGE NUMBER(3),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO CUSTOMERS (ID, FIRST_NAME, LAST_NAME, AGE) VALUES (1, 'John', 'Doe', 30);
INSERT INTO CUSTOMERS (ID, FIRST_NAME, LAST_NAME, AGE) VALUES (2, 'Jane', 'Smith', 25);

CREATE TABLE TEMPLATE_TEST (
    ID NUMBER(10) PRIMARY KEY,
    TEXT_COL VARCHAR2(100) NOT NULL,
    NUM_COL NUMBER(10,2),
    BOOL_COL BOOLEAN,
    DATE_COL DATE,
    GENERIC_COL BLOB
);
