# Configuración de la base de datos (H2 para el showcase)
hibernate.connection.url=jdbc:h2:mem:showcase_db;DB_CLOSE_DELAY=-1;MODE=Oracle
hibernate.connection.driver_class=org.h2.Driver
hibernate.default_schema=PUBLIC

# Configuración del generador OpenAPI
api.title=Showcase API
api.version=1.0.1
templates.path=openapi-generator-showcase/src/main/resources/templates
