DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS ORDERS;

CREATE TABLE PRODUCTS (
    ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100),
    PRICE NUMBER(10,2)
);

CREATE TABLE ORDERS (
    ID NUMBER(10) PRIMARY KEY,
    PRODUCT_ID NUMBER(10),
    QUANTITY NUMBER(5)
);
