dependencies {
    implementation project(':openapi-generator-core')
    implementation project(':openapi-generator-database-exporter')

    // Drivers JDBC necesarios para el showcase
    implementation 'com.h2database:h2:2.2.224'

    // JUnit para el test que actúe como ejecutable
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.test {
    useJUnitPlatform()
}
