DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS TEMPLATE_TEST;

CREATE TABLE PRODUCTS (
    ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(100),
    PRICE NUMBER(10,2)
);

CREATE TABLE ORDERS (
    ID NUMBER(10) PRIMARY KEY,
    PRODUCT_ID NUMBER(10),
    QUANTITY NUMBER(5)
);

CREATE TABLE TEMPLATE_TEST (
    ID NUMBER(10) PRIMARY KEY,
    TEXT_COL VARCHAR2(100) NOT NULL,
    NUM_COL NUMBER(10,2),
    BOOL_COL BOOLEAN,
    DATE_COL DATE,
    GENERIC_COL BLOB
);
